#!/bin/bash

conda install -c conda-forge xeus-cling
jupyter lab workspaces import binder/workspace.json

cd ~/dsl
g++ skel.cpp -o skel
g++ gen.cpp lexer.cpp parse.cpp -o gen

mv skel ~/bin/skel
mv gen ~/bin/gen

chmod 755 ~/bin/skel
chmod 755 ~/bin/gen